'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Stock_Item_Form
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Heading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Heading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RB_SSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RB_SSE As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RB_Others control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RB_Others As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''P_SSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P_SSE As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''L_Item_Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_Item_Desc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Item_Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Item_Desc As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''L_PO_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_PO_No As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PO_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PO_No As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_PO_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_PO_Date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PO_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PO_Date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_PO_Qty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_PO_Qty As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PO_Qty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PO_Qty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_Firm_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_Firm_Name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Firm_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Firm_Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_S_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_S_Date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''S_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S_Date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_S_Qty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_S_Qty As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''S_Qty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S_Qty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_I_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_I_Date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''I_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I_Date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_I_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_I_Status As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''I_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I_Status As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_R_S_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_R_S_Date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''R_S_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_S_Date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_I_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_I_Remarks As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''I_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I_Remarks As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''P_Others control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P_Others As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''L_I_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_I_D As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''O_Item_Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents O_Item_Desc As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''L_P_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_P_No As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''P_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P_No As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_P_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_P_Date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''P_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P_Date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_P_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_P_Q As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''P_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P_Q As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_F_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_F_Name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''F_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F_Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_Sup_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_Sup_Date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Sup_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sup_Date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_S_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_S_Q As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''S_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S_Q As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_I_Done_By control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_I_Done_By As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''I_Done_By control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I_Done_By As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_Ins_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_Ins_Date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Ins_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ins_Date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_I_S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_I_S As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''I_S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I_S As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''L_Ins_Rem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_Ins_Rem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Ins_Rem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ins_Rem As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit As Global.System.Web.UI.WebControls.Button
End Class
