Menu.prototype.cssFile = '/ppms/menus/skins/officexp/officexp.css';

Menu.prototype.cssFile = '/ppms/menus/skins/officexp/officexp.css';
var m_00= new Menu();var m_01= new Menu();var m_02= new Menu();var m_03= new Menu();var m_04= new Menu();var m_05= new Menu();var m_06= new Menu();var m_07= new Menu();var m_08= new Menu();var m_09= new Menu();var m_11= new Menu();var m_12= new Menu();var m_13= new Menu();var m_20= new Menu();var m_21= new Menu();
var tmp;
m_00.add(tmp = new MenuItem("General Codes",null,null, m_01) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Designation Codes",null,null, m_02) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Scale Table",null,null, m_03) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Leave Rule Master",null,null, m_04) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Earning/Deduction Dir",null,null, m_05) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Bank Directory",null,null, m_06) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Quarter Master",null,null, m_07) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Rate Table",null,null, m_08) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Rule Table",null,null, m_09) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("General System File","/ppms/payrollSystemFile.aspx?mode=edit"));tmp.mnemonic = '';m_00.add(tmp = new MenuItem("Common Earning/Deduction",null,null, m_11) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Income Tax Rules",null,null, m_12) );
tmp.mnemonic = '';
m_00.add(tmp = new MenuItem("Work Order",null,null, m_13) );
tmp.mnemonic = '';
m_01.add(tmp = new MenuItem("Code Type Maintenance",null,null, m_20) );
tmp.mnemonic = '';
m_01.add(tmp = new MenuItem("Code Maintenance",null,null, m_21) );
tmp.mnemonic = '';
m_01.add(tmp = new MenuItem("Checklist","/ppms/rptGeneral.aspx?rptName=ppmsCodes"));tmp.mnemonic = '';m_02.add(tmp = new MenuItem("Create","/ppms/designationDirectory.aspx?mode=add"));tmp.mnemonic = '';m_02.add(tmp = new MenuItem("Edit","/ppms/designationDirectory.aspx?mode=edit"));tmp.mnemonic = '';m_02.add(tmp = new MenuItem("View","/ppms/designationDirectory.aspx?mode=view"));tmp.mnemonic = '';m_02.add(tmp = new MenuItem("Check List","/ppms/Reports/formats/CodeDirectory/allocationwise.aspx?mode=CodeDirectory-Designations"));tmp.mnemonic = '';m_03.add(tmp = new MenuItem("Create","/ppms/scaleCode.aspx?mode=add"));tmp.mnemonic = '';m_03.add(tmp = new MenuItem("Edit","/ppms/scaleCode.aspx?mode=edit"));tmp.mnemonic = '';m_03.add(tmp = new MenuItem("View","/ppms/scaleCode.aspx?mode=view"));tmp.mnemonic = '';m_03.add(tmp = new MenuItem("Check List","/ppms/Reports/formats/CodeDirectory/allocationwise.aspx?mode=CodeDirectory-ScaleCodes"));tmp.mnemonic = '';m_04.add(tmp = new MenuItem("Create","/ppms/leaveMaster.aspx?mode=add"));tmp.mnemonic = '';m_04.add(tmp = new MenuItem("Edit","/ppms/leaveMaster.aspx?mode=edit"));tmp.mnemonic = '';m_04.add(tmp = new MenuItem("View","/ppms/leaveMaster.aspx?mode=view"));tmp.mnemonic = '';m_04.add(tmp = new MenuItem("Check List","/ppms/Reports/formats/rptrules/rptLeaves.aspx?mode=rptLeaveCodes"));tmp.mnemonic = '';m_05.add(tmp = new MenuItem("Create","/ppms/earningDeductionCodes.aspx?mode=add"));tmp.mnemonic = '';m_05.add(tmp = new MenuItem("Edit","/ppms/earningDeductionCodes.aspx?mode=edit"));tmp.mnemonic = '';m_05.add(tmp = new MenuItem("View","/ppms/earningDeductionCodes.aspx?mode=view"));tmp.mnemonic = '';m_05.add(tmp = new MenuItem("Check List","/ppms/Reports/formats/CheckList/Checklist.aspx?mode=ChecklistEarningsDeductions"));tmp.mnemonic = '';m_06.add(tmp = new MenuItem("Create","/ppms/bankDirectory.aspx?mode=add"));tmp.mnemonic = '';m_06.add(tmp = new MenuItem("Edit","/ppms/bankDirectory.aspx?mode=edit"));tmp.mnemonic = '';m_06.add(tmp = new MenuItem("View","/ppms/bankDirectory.aspx?mode=view"));tmp.mnemonic = '';m_06.add(tmp = new MenuItem("Check List","/ppms/Reports/formats/CheckList/Checklist.aspx?mode=ChecklistBankdetails"));tmp.mnemonic = '';m_07.add(tmp = new MenuItem("Create","/ppms/quarterMaster.aspx?mode=add"));tmp.mnemonic = '';m_07.add(tmp = new MenuItem("Edit","/ppms/quarterMaster.aspx?mode=edit"));tmp.mnemonic = '';m_07.add(tmp = new MenuItem("Delete","/ppms/quarterMaster.aspx?mode=delete"));tmp.mnemonic = '';m_07.add(tmp = new MenuItem("View","/ppms/quarterMaster.aspx?mode=view"));tmp.mnemonic = '';m_08.add(tmp = new MenuItem("Create","/ppms/rateTable.aspx?mode=add"));tmp.mnemonic = '';m_08.add(tmp = new MenuItem("Edit","/ppms/rateTable.aspx?mode=edit"));tmp.mnemonic = '';m_08.add(tmp = new MenuItem("View","/ppms/rateTable.aspx?mode=view"));tmp.mnemonic = '';m_08.add(tmp = new MenuItem("Check List","/ppms/Reports/formats/rptrules/rptRules.aspx?mode=rptRateTable"));tmp.mnemonic = '';m_09.add(tmp = new MenuItem("Create","/ppms/ruleTable.aspx?mode=add"));tmp.mnemonic = '';m_09.add(tmp = new MenuItem("Edit","/ppms/ruleTable.aspx?mode=edit"));tmp.mnemonic = '';m_09.add(tmp = new MenuItem("View","/ppms/ruleTable.aspx?mode=view"));tmp.mnemonic = '';m_09.add(tmp = new MenuItem("Check List","/ppms/Reports/formats/rptRules/rptRules.aspx?mode=rptRuleTable"));tmp.mnemonic = '';m_11.add(tmp = new MenuItem("Create","/ppms/commonEarningDeductionCodes.aspx?mode=add"));tmp.mnemonic = '';m_11.add(tmp = new MenuItem("Delete","/ppms/commonEarningDeductionCodes.aspx?mode=delete"));tmp.mnemonic = '';m_11.add(tmp = new MenuItem("View","/ppms/commonEarningDeductionCodes.aspx?mode=view"));tmp.mnemonic = '';m_12.add(tmp = new MenuItem("Create","/ppms/incomeTaxRules.aspx?mode=add"));tmp.mnemonic = '';m_12.add(tmp = new MenuItem("Modify","/ppms/incomeTaxRules.aspx?mode=edit"));tmp.mnemonic = '';m_12.add(tmp = new MenuItem("Delete","/ppms/incomeTaxRules.aspx?mode=delete"));tmp.mnemonic = '';m_12.add(tmp = new MenuItem("View","/ppms/incomeTaxRules.aspx?mode=view"));tmp.mnemonic = '';m_12.add(tmp = new MenuItem("Check List","/ppms/Reports/formats/rptrules/rptRules.aspx?mode=rptITRules"));tmp.mnemonic = '';m_13.add(tmp = new MenuItem("Create","/ppms/workOrderDetails.aspx?mode=add"));tmp.mnemonic = '';m_13.add(tmp = new MenuItem("Modify","/ppms/workOrderDetails.aspx?mode=edit"));tmp.mnemonic = '';m_13.add(tmp = new MenuItem("View","/ppms/workOrderDetails.aspx?mode=view"));tmp.mnemonic = '';m_13.add(tmp = new MenuItem("Delete","/ppms/workOrderDetails.aspx?mode=delete"));tmp.mnemonic = '';m_13.add(tmp = new MenuItem("Checklist","/ppms/Reports/formats/rptrules/rptRules.aspx?mode=rptWorkOrders"));tmp.mnemonic = '';
var menuBar = new MenuBar();
menuBar.add( tmp = new MenuButton("Setup", m_00) );
tmp.mnemonic = '';

menuBar.write();
