Menu.prototype.cssFile = '/ppms/menus/skins/officexp/officexp.css';

Menu.prototype.cssFile = '/ppms/menus/skins/officexp/officexp.css';
var mM01= new Menu();var mSE1= new Menu();var mY03= new Menu();var mA05= new Menu();var mTR01= new Menu();var mTR4= new Menu();var mM11= new Menu();var mM12= new Menu();var mSE2= new Menu();var mSE3= new Menu();var mSE8= new Menu();var mSE12= new Menu();var mSE16= new Menu();var mSE21= new Menu();var mTR02= new Menu();var mTR07= new Menu();
var tmp;
mA05.add(tmp = new MenuItem("Setup",null,null, mTR01) );
tmp.mnemonic = '';
mA05.add(tmp = new MenuItem("Create Nomination Noting","/ppms/training/trainingDueListOfOfficers.aspx?mode=create"));tmp.mnemonic = '';mA05.add(tmp = new MenuItem("Add Employee","/ppms/training/trainingDueListOfOfficers.aspx?mode=add"));tmp.mnemonic = '';mA05.add(tmp = new MenuItem("Edit Employee","/ppms/training/trainingDueListOfOfficers.aspx?mode=edit"));tmp.mnemonic = '';mA05.add(tmp = new MenuItem("Delete Employee","/ppms/training/trainingDueListOfOfficers.aspx?mode=delete"));tmp.mnemonic = '';mA05.add(tmp = new MenuItem("Course","/ppms/training/frmCourse.aspx?mode=view"));tmp.mnemonic = '';mA05.add(tmp = new MenuItem("Generate Memorandum","/ppms/training/frmOfficeOrderNumber.aspx"));tmp.mnemonic = '';mA05.add(tmp = new MenuItem("Institute",null,null, mTR4) );
tmp.mnemonic = '';
mM01.add(tmp = new MenuItem("Entry of Extra Vacancies",null,null, mM11) );
tmp.mnemonic = '';
mM01.add(tmp = new MenuItem("Quota Register",null,null, mM12) );
tmp.mnemonic = '';
mM01.add(tmp = new MenuItem("Roster","/ppms//bos/assesmentofVacancies.aspx"));tmp.mnemonic = '';mM01.add(tmp = new MenuItem("BOS Posts Updation","/ppms/bos/RosterEdit.aspx?mode=add"));tmp.mnemonic = '';mM01.add(tmp = new MenuItem("Roster Sanctions Updation","/ppms/bos/frmRosterHeaderUpdation.aspx"));tmp.mnemonic = '';mSE1.add(tmp = new MenuItem("Direct Recruitment",null,null, mSE2) );
tmp.mnemonic = '';
mSE1.add(tmp = new MenuItem("Promotion",null,null, mSE3) );
tmp.mnemonic = '';
mY03.add(tmp = new MenuItem("Employee Pension Application","/ppms/Settlement/employeePension.aspx"));tmp.mnemonic = '';mY03.add(tmp = new MenuItem("Application Forms","/ppms/Settlement/pensionReports.aspx"));tmp.mnemonic = '';mY03.add(tmp = new MenuItem("Settlement Calculation","/ppms/Settlement/pensionCalculation.aspx"));tmp.mnemonic = '';mY03.add(tmp = new MenuItem("PPO Report","/ppms/Settlement/printPPO.aspx"));tmp.mnemonic = '';mY03.add(tmp = new MenuItem("CGEGIS Acc. Amt.","/ppms/Settlement/CGEIS.aspx"));tmp.mnemonic = '';mM11.add(tmp = new MenuItem("Add","/ppms//bos/entryofExtraVacancies.aspx?mode=add"));tmp.mnemonic = '';mM11.add(tmp = new MenuItem("Modify","/ppms//bos/entryofExtraVacancies.aspx?mode=edit"));tmp.mnemonic = '';mM11.add(tmp = new MenuItem("Delete","/ppms//bos/entryofExtraVacancies.aspx?mode=delete"));tmp.mnemonic = '';mM11.add(tmp = new MenuItem("Query","/ppms//bos/entryofExtraVacancies.aspx?mode=view"));tmp.mnemonic = '';mM12.add(tmp = new MenuItem("Add","/ppms//bos/quotaRegister.aspx?mode=add"));tmp.mnemonic = '';mM12.add(tmp = new MenuItem("Modify","/ppms//bos/quotaRegister.aspx?mode=edit"));tmp.mnemonic = '';mSE2.add(tmp = new MenuItem("Requisition for Cand.","/ppms/Selection/requisitionforCandidates.aspx"));tmp.mnemonic = '';mSE2.add(tmp = new MenuItem("Placing of Indent on RRB","/ppms/Selection/placingofIndent.aspx"));tmp.mnemonic = '';mSE2.add(tmp = new MenuItem("ConfirmationOfIndent","/ppms/Selection/vacancyConfirmation.aspx"));tmp.mnemonic = '';mSE2.add(tmp = new MenuItem("Reports","/ppms/Selection/directRecruitmentReports.aspx"));tmp.mnemonic = '';mSE3.add(tmp = new MenuItem("Employee Selection List",null,null, mSE8) );
tmp.mnemonic = '';
mSE3.add(tmp = new MenuItem("Employee Selection List Reports","/ppms/Selection/selectionReports.aspx"));tmp.mnemonic = '';mSE3.add(tmp = new MenuItem("Test Details",null,null, mSE12) );
tmp.mnemonic = '';
mSE3.add(tmp = new MenuItem("TestDetailReports","/ppms/Selection/testReports.aspx"));tmp.mnemonic = '';mSE3.add(tmp = new MenuItem("Viva/Interview Details",null,null, mSE16) );
tmp.mnemonic = '';
mSE3.add(tmp = new MenuItem("Viva/Interview Reports","/ppms/Selection/vivaReports.aspx"));tmp.mnemonic = '';mSE3.add(tmp = new MenuItem("Promotion Details",null,null, mSE21) );
tmp.mnemonic = '';
mSE3.add(tmp = new MenuItem("Promotion Reports","/ppms/Selection/PromotionReports.aspx"));tmp.mnemonic = '';mTR01.add(tmp = new MenuItem("Institute Details",null,null, mTR02) );
tmp.mnemonic = '';
mTR01.add(tmp = new MenuItem("Training Schedule",null,null, mTR07) );
tmp.mnemonic = '';
mTR4.add(tmp = new MenuItem("Add","/ppms/training/trainingInstituteDetails.aspx?mode=add"));tmp.mnemonic = '';mTR4.add(tmp = new MenuItem("Edit","/ppms/training/trainingInstituteDetails.aspx?mode=edit"));tmp.mnemonic = '';mTR4.add(tmp = new MenuItem("Delete","/ppms/training/trainingInstituteDetails.aspx?mode=delete"));tmp.mnemonic = '';mTR4.add(tmp = new MenuItem("View","/ppms/training/trainingFeedBack.aspx?mode=view"));tmp.mnemonic = '';mSE12.add(tmp = new MenuItem("Add","/ppms/Selection/testDetails.aspx?mode=add"));tmp.mnemonic = '';mSE12.add(tmp = new MenuItem("Edit","/ppms/Selection/testDetails.aspx?mode=edit"));tmp.mnemonic = '';mSE12.add(tmp = new MenuItem("View","/ppms/Selection/testDetails.aspx?mode=view"));tmp.mnemonic = '';mSE16.add(tmp = new MenuItem("Add","/ppms/Selection/vivaDetails.aspx?mode=add"));tmp.mnemonic = '';mSE16.add(tmp = new MenuItem("Edit","/ppms/Selection/vivaDetails.aspx?mode=edit"));tmp.mnemonic = '';mSE16.add(tmp = new MenuItem("View","/ppms/Selection/vivaDetails.aspx?mode=view"));tmp.mnemonic = '';mSE21.add(tmp = new MenuItem("Add","/ppms/Selection/PromotionDetails.aspx?mode=add"));tmp.mnemonic = '';mSE8.add(tmp = new MenuItem("Add","/ppms/Selection/employeeSelection.aspx?mode=add"));tmp.mnemonic = '';mSE8.add(tmp = new MenuItem("Edit","/ppms/Selection/employeeSelection.aspx?mode=edit"));tmp.mnemonic = '';mSE8.add(tmp = new MenuItem("View","/ppms/Selection/employeeSelection.aspx?mode=view"));tmp.mnemonic = '';mTR02.add(tmp = new MenuItem("Add","/ppms/training/trainingInstituteDetails.aspx?mode=add"));tmp.mnemonic = '';mTR02.add(tmp = new MenuItem("Edit","/ppms/training/trainingInstituteDetails.aspx?mode=edit"));tmp.mnemonic = '';mTR02.add(tmp = new MenuItem("View",""));tmp.mnemonic = '';mTR07.add(tmp = new MenuItem("Add","/ppms/training/trainingSchedule.aspx?mode=add"));tmp.mnemonic = '';mTR07.add(tmp = new MenuItem("Edit","/ppms/training/frmCourse.aspx?mode=edit"));tmp.mnemonic = '';mTR07.add(tmp = new MenuItem("View","/ppms/training/trainingSchedule.aspx?mode=view"));tmp.mnemonic = '';mTR07.add(tmp = new MenuItem("Delete","/ppms/training/trainingSchedule.aspx?mode=delete"));tmp.mnemonic = '';mSE21.add(tmp = new MenuItem("Edit","/ppms/Selection/PromotionDetails.aspx?mode=edit"));tmp.mnemonic = '';mSE21.add(tmp = new MenuItem("View","/ppms/Selection/PromotionDetails.aspx?mode=view"));tmp.mnemonic = '';
var menuBar = new MenuBar();
menuBar.add( tmp = new MenuButton("Book Of Sanction", mM01) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Selection", mSE1) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Settlement", mY03) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Training", mA05) );
tmp.mnemonic = '';

menuBar.write();
