Menu.prototype.cssFile = '/ppms/menus/skins/officexp/officexp.css';

Menu.prototype.cssFile = '/ppms/menus/skins/officexp/officexp.css';
var m001= new Menu();var m002= new Menu();var m003= new Menu();var m004= new Menu();var m086= new Menu();var m045= new Menu();var m012= new Menu();var m079= new Menu();var m299= new Menu();var m139= new Menu();var m083= new Menu();var m597= new Menu();var m322= new Menu();var m323= new Menu();var m308= new Menu();
var tmp;
m001 .add(tmp = new MenuItem("Emp Suspense",null,null, m086) );
tmp.mnemonic = ' ';
m002 .add(tmp = new MenuItem("Bills",null,null, m045) );
tmp.mnemonic = ' ';
m002 .add(tmp = new MenuItem("EDIT PF BANK AND A/C","/ppms/fms/pfBankAccount.aspx"));tmp.mnemonic = ' ';m002 .add(tmp = new MenuItem("CO7 Posting",null,null, m012) );
tmp.mnemonic = ' ';
m002 .add(tmp = new MenuItem("Journal Voucher",null,null, m079) );
tmp.mnemonic = ' ';
m002 .add(tmp = new MenuItem("Transfer Certificate",null,null, m299) );
tmp.mnemonic = ' ';
m002 .add(tmp = new MenuItem("Loan trans edit","/ppms/fms/LoanTransEdit.aspx"));tmp.mnemonic = ' ';m002 .add(tmp = new MenuItem("Edit PF Trans","/ppms/fms/editpfTrans.aspx"));tmp.mnemonic = ' ';m003 .add(tmp = new MenuItem("PF","/ppms/fms/frmPFQueryDetails.aspx"));tmp.mnemonic = ' ';m003.add(tmp = new MenuItem("PF Bills Register","/ppms/fms/reports/rptPFBills.aspx?rptName=rptPFBillsRegister.rpt"));tmp.mnemonic = '';m004 .add(tmp = new MenuItem("CO6 Register","/ppms/fms/Reports/rptBillCO6Register.aspx?rptName=rptConblCO6Register.rpt"));tmp.mnemonic = ' ';m004 .add(tmp = new MenuItem("CO7 Register","/ppms/fms/reports/rpBillCo7Register.aspx?rptName=rptCO7Register.rpt"));tmp.mnemonic = ' ';m004 .add(tmp = new MenuItem("On Demand",null,null, m139) );
tmp.mnemonic = ' ';
m004 .add(tmp = new MenuItem("PF Bills Register","/ppms/fms/reports/rptPFBills.aspx?rptName=rptPFBillsRegister.rpt"));tmp.mnemonic = ' ';m012 .add(tmp = new MenuItem("Posting","/ppms/fms/co7Posting.aspx"));tmp.mnemonic = ' ';m012 .add(tmp = new MenuItem("Print","/ppms/fms/Reports/frmPrintCheques.aspx"));tmp.mnemonic = ' ';m045 .add(tmp = new MenuItem("PF Bill","/ppms/fms/pfBill.aspx"));tmp.mnemonic = ' ';m045 .add(tmp = new MenuItem("General",null,null, m083) );
tmp.mnemonic = ' ';
m079 .add(tmp = new MenuItem("Add","/ppms/fms/journalVoucher.aspx?mode=add"));tmp.mnemonic = ' ';m079 .add(tmp = new MenuItem("Edit","/ppms/fms/journalVoucher.aspx?mode=edit"));tmp.mnemonic = ' ';m079 .add(tmp = new MenuItem("Print","/ppms/fms/reports/jvPrinting.aspx?mode=add"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("Add","/ppms/fms/empSuspense.aspx?mode=add"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("Edit","/ppms/fms/empSuspense.aspx?mode=edit"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("Delete","/ppms/fms/empSuspense.aspx?mode=delete"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("View","/ppms/fms/empSuspense.aspx?mode=view"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("Checklist","/ppms/fms/reports/rptEmpSuspenseCheckLists.aspx?rptName=rptEmployeeSuspenseCheckList.rpt"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("Edit Transactions","/ppms/fms/EditEmpSuspense.aspx"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("Update","/ppms/fms/pfUpdate.aspx"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("Register","/ppms/fms/reports/rptEmployeeRegister.aspx?rptName=rptEmpSuspRegister.rpt"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("JV for Employee suspense","/ppms/fms/jvEmployeeSuspense.aspx"));tmp.mnemonic = ' ';m086 .add(tmp = new MenuItem("Employee Suspense Closing","/ppms/fms/chequebillClosing.aspx?title=E&taskid=376"));tmp.mnemonic = ' ';m139 .add(tmp = new MenuItem("Alloc wise Transaction List","/ppms/fms/Reports/AllocationWise.aspx?rptName=AllocationTranList.rpt"));tmp.mnemonic = ' ';m139 .add(tmp = new MenuItem("Transactions Checklist",null,null, m597) );
tmp.mnemonic = ' ';
m299 .add(tmp = new MenuItem("Inward TC",null,null, m322) );
tmp.mnemonic = ' ';
m299 .add(tmp = new MenuItem("Outward TC",null,null, m323) );
tmp.mnemonic = ' ';
m083 .add(tmp = new MenuItem("Add","/ppms/fms/generalCo6Entry.aspx?mode=add"));tmp.mnemonic = ' ';m083 .add(tmp = new MenuItem("Edit","/ppms/fms/generalCo6Entry.aspx?mode=edit"));tmp.mnemonic = ' ';m322 .add(tmp = new MenuItem("Employee TC",null,null, m308) );
tmp.mnemonic = ' ';
m323 .add(tmp = new MenuItem("Cash","/ppms/fms/FMTRNJV"));tmp.mnemonic = ' ';m323 .add(tmp = new MenuItem("PF transfer","/ppms/fms/FMPFTC"));tmp.mnemonic = ' ';m323 .add(tmp = new MenuItem("Print certificate","/ppms/fms/reports/rptOutwardTcPrint.aspx?rptName=rptOutwardsPrintTC.rpt"));tmp.mnemonic = ' ';m597 .add(tmp = new MenuItem("PF","/ppms/fms/Reports/rptCheckLists.aspx?rptName=rptFmrpf.rpt"));tmp.mnemonic = ' ';m308 .add(tmp = new MenuItem("Entry","/ppms/fms/employeeTCScreen.aspx?mode=add"));tmp.mnemonic = ' ';m308 .add(tmp = new MenuItem("Edit","/ppms/fms/employeeTCScreen.aspx?mode=edit"));tmp.mnemonic = ' ';
var menuBar = new MenuBar();
menuBar.add( tmp = new MenuButton("Maintenance", m001) );
tmp.mnemonic = ' ';
menuBar.add( tmp = new MenuButton("Transactions", m002) );
tmp.mnemonic = ' ';
menuBar.add( tmp = new MenuButton("Query", m003) );
tmp.mnemonic = ' ';
menuBar.add( tmp = new MenuButton("Reports", m004) );
tmp.mnemonic = ' ';

menuBar.write();
