Menu.prototype.cssFile = '/wap/menus/skins/officexp/officexp.css';

Menu.prototype.cssFile = '/wap/menus/skins/officexp/officexp.css';
var mH01= new Menu();var mV00= new Menu();var mL02= new Menu();var mLB00= new Menu();var mA03= new Menu();var mMGM= new Menu();var mHS01= new Menu();var mL03= new Menu();var mL10= new Menu();var mL14= new Menu();var mLB06= new Menu();var mLB01= new Menu();var mV01= new Menu();var mV02= new Menu();var mL04= new Menu();
var tmp;
mA03.add(tmp = new MenuItem("Transport - Van Rate","/wap/ppms/miscEDs/pbranchTransport.aspx"));tmp.mnemonic = '';mH01.add(tmp = new MenuItem("Post Allotment",null,null, mHS01) );
tmp.mnemonic = '';
mL02.add(tmp = new MenuItem("Leave Application",null,null, mL03) );
tmp.mnemonic = '';
mL02.add(tmp = new MenuItem("Leave Master",null,null, mL10) );
tmp.mnemonic = '';
mL02.add(tmp = new MenuItem("Leave Special Debit/Credit",null,null, mL14) );
tmp.mnemonic = '';
mLB00.add(tmp = new MenuItem("Issue Book",null,null, mLB06) );
tmp.mnemonic = '';
mLB00.add(tmp = new MenuItem("Library Master",null,null, mLB01) );
tmp.mnemonic = '';
mMGM.add(tmp = new MenuItem("Post Messages","/wap/ppms/frmNoticeBoard.aspx"));tmp.mnemonic = '';mV00.add(tmp = new MenuItem("Complaints",null,null, mV01) );
tmp.mnemonic = '';
mV00.add(tmp = new MenuItem("Remarks",null,null, mV02) );
tmp.mnemonic = '';
mHS01.add(tmp = new MenuItem("ADD","/wap/ppms/quest/hrHolidayHomeApproval.aspx?mode=add"));tmp.mnemonic = '';mHS01.add(tmp = new MenuItem("EDIT","/wap/ppms/quest/hrHolidayHomeApproval.aspx?mode=edit"));tmp.mnemonic = '';mHS01.add(tmp = new MenuItem("DELETE","/wap/ppms/quest/hrHolidayHomeApproval.aspx?mode=delete"));tmp.mnemonic = '';mL03.add(tmp = new MenuItem("Application Posting",null,null, mL04) );
tmp.mnemonic = '';
mL03.add(tmp = new MenuItem("Posting Leave Sanction","/wap/ppms/leave/postSanctionToApplicationForLeave.aspx?mode=post"));tmp.mnemonic = '';mL04.add(tmp = new MenuItem("Add","/wap/ppms/leave/leaveApplicationform.aspx?mode=add&task_id=L05"));tmp.mnemonic = '';mL04.add(tmp = new MenuItem("Delete","/wap/ppms/leave/editApplicationForLeave.aspx?mode=delete"));tmp.mnemonic = '';mL04.add(tmp = new MenuItem("Application Printing","/wap/ppms/Reports/formats/ApplicationForms/rptLeaveApplication.aspx?mode=rptLeaveApplication"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Add","/wap/ppms/leave/employeeLeaveMaster.aspx?mode=add"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Edit","/wap/ppms/leave/employeeLeaveMaster.aspx?mode=edit"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Delete","/wap/ppms/leave/employeeLeaveMaster.aspx?mode=delete"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Leave Crediting - I half","/wap/ppms/leave/FstHalfLeaveCredit.aspx"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Leave Crediting - II half","/wap/ppms/leave/SecondHalfLeaveCredit.aspx"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Retrospective Leave Cr/Db","/wap/ppms/leave/leaveRetrospectivePosting.aspx"));tmp.mnemonic = '';mL14.add(tmp = new MenuItem("Add","/wap/ppms/leave/leaveSpecialDeditCredit.aspx?mode=add"));tmp.mnemonic = '';mL14.add(tmp = new MenuItem("Edit","/wap/ppms/leave/leaveSpecialDeditCredit.aspx?mode=edit"));tmp.mnemonic = '';mL14.add(tmp = new MenuItem("Delete","/wap/ppms/leave/leaveSpecialDeditCredit.aspx?mode=delete"));tmp.mnemonic = '';mLB01.add(tmp = new MenuItem("Add","/wap/ppms/library/libraryMaster.aspx?mode=add"));tmp.mnemonic = '';mLB01.add(tmp = new MenuItem("Edit","/wap/ppms/library/libraryMaster.aspx?mode=edit"));tmp.mnemonic = '';mLB01.add(tmp = new MenuItem("Delete","/wap/ppms/library/libraryMaster.aspx?mode=delete"));tmp.mnemonic = '';mLB01.add(tmp = new MenuItem("View","/wap/ppms/library/libraryMaster.aspx?mode=view"));tmp.mnemonic = '';mLB06.add(tmp = new MenuItem("Issue","/wap/ppms/library/libraryTransactions.aspx?mode=issue"));tmp.mnemonic = '';mLB06.add(tmp = new MenuItem("Return","/wap/ppms/library/libraryTransactions.aspx?mode=return"));tmp.mnemonic = '';mV01.add(tmp = new MenuItem("View All","/wap/ppms/greivances/viewAll.aspx"));tmp.mnemonic = '';mV02.add(tmp = new MenuItem("Remarks-New Cases","/wap/ppms/greivances/answerGreivances.aspx?mode=add"));tmp.mnemonic = '';mV02.add(tmp = new MenuItem("View New Complaints","/wap/ppms/rptGeneral.aspx?rptName=greivance_new_comp"));tmp.mnemonic = '';mV02.add(tmp = new MenuItem("View Remarks made","/wap/ppms/rptGeneral.aspx?rptName=greivance_remakrs"));tmp.mnemonic = '';mV02.add(tmp = new MenuItem("View Particular Employee","/wap/ppms/greivances/grievanceLogin.aspx?mode=view"));tmp.mnemonic = '';mV02.add(tmp = new MenuItem("Delete Old Cases","/wap/ppms/greivances/grDeleteOldCasses.aspx"));tmp.mnemonic = '';
var menuBar = new MenuBar();
menuBar.add( tmp = new MenuButton("Holiday Home", mH01) );
tmp.mnemonic = ' ';
menuBar.add( tmp = new MenuButton("Grievance Monitoring", mV00) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Leave Accounting", mL02) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Library", mLB00) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Misc. E/Ds", mA03) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Messages", mMGM) );
tmp.mnemonic = '';

menuBar.write();
