Menu.prototype.cssFile = '/wap/menus/skins/officexp/officexp.css';

Menu.prototype.cssFile = '/wap/menus/skins/officexp/officexp.css';
var m004= new Menu();var mM01= new Menu();var mP01= new Menu();
var mG00= new Menu();var mL02= new Menu();var m006= new Menu();
var m278= new Menu();var mQ00= new Menu();
var mC01= new Menu();var mLR01= new Menu();var mQYM= new Menu();var m167= new Menu();
var m366= new Menu();var m281= new Menu();
var m282= new Menu();var mC39= new Menu();var mC12= new Menu();
var mC20= new Menu();var mC21= new Menu();
var mC22= new Menu();var mC23= new Menu();var mC24= new Menu();
var mC25= new Menu();var mC26= new Menu();var mC011= new Menu();
var mG01= new Menu();var mG02= new Menu();var mG25= new Menu();
var mG30= new Menu();var mG35= new Menu();var mG030= new Menu();
var mL03= new Menu();var mL10= new Menu();var mL50= new Menu();
var mL14= new Menu();var mM11= new Menu();var mM12= new Menu();var mM13= new Menu();
var mM15= new Menu();var mP101= new Menu();var mQ001= new Menu();var mQ01= new Menu();
var mQ02= new Menu();var mQ03= new Menu();var m359= new Menu();var m299= new Menu();
var m367= new Menu();var m368= new Menu();var mC59= new Menu();var mL04= new Menu();
var mQ002= new Menu();var mC60= new Menu();var mG21= new Menu();
var tmp;
m004.add(tmp = new MenuItem("Misc. Attendance",null,null, m167) );
tmp.mnemonic = '';
m006.add(tmp = new MenuItem("Payroll Process","/wap/ppms/payroll/payroll.aspx?mode=P"));tmp.mnemonic = '';m006.add(tmp = new MenuItem("View",null,null, m366) );
tmp.mnemonic = '';
m006.add(tmp = new MenuItem("Payslip","/wap/ppms/reports/formats/rptpayroll/rptpayslip.aspx?mode=rptPaySlip"));tmp.mnemonic = '';m278.add(tmp = new MenuItem("Employee Details",null,null, m281) );
tmp.mnemonic = '';
m278.add(tmp = new MenuItem("Career Events",null,null, m282) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Bank",null,null, mC39) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Pay Rates","/wap/ppms/PPM027"));tmp.mnemonic = '';mC01.add(tmp = new MenuItem("Misc.Attendance",null,null, mC12) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Misc. Earn/Dedns",null,null, mC20) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Other Railways",null,null, mC21) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Loans/Advances",null,null, mC22) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Arrears",null,null, mC23) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Policies",null,null, mC24) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Other Fixed E/Ds",null,null, mC25) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Memberships",null,null, mC26) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Supervisers Off Duty",null,null, mC011) );
tmp.mnemonic = ' ';
mG00.add(tmp = new MenuItem("Loan Applications",null,null, mG01) );
tmp.mnemonic = '';
mG00.add(tmp = new MenuItem("Posting Loan Sanctions",null,null, mG02) );
tmp.mnemonic = '';
mG00.add(tmp = new MenuItem("Application Prints",null,null, mG25) );
tmp.mnemonic = '';
mG00.add(tmp = new MenuItem("Noting Prints",null,null, mG30) );
tmp.mnemonic = '';
mG00.add(tmp = new MenuItem("Generate Office Order Number","/wap/ppms/loans/loansOfficeOrderNumber.aspx"));tmp.mnemonic = '';mG00.add(tmp = new MenuItem("Office Order Number Prints",null,null, mG35) );
tmp.mnemonic = '';
mG00.add(tmp = new MenuItem("Post to Supplementary","/wap/ppms/loans/loanPostToSupPay.aspx?post=S"));tmp.mnemonic = '';mG00.add(tmp = new MenuItem("Post to Payroll","/wap/ppms/loans/loanPostToSupPay.aspx?post=P"));tmp.mnemonic = '';mG00.add(tmp = new MenuItem("Edit Application",null,null, mG030) );
tmp.mnemonic = ' ';
mL02.add(tmp = new MenuItem("Leave Application",null,null, mL03) );
tmp.mnemonic = '';
mL02.add(tmp = new MenuItem("Leave Master",null,null, mL10) );
tmp.mnemonic = '';
mL02.add(tmp = new MenuItem("Leave/Absence",null,null, mL50) );
tmp.mnemonic = '';
mL02.add(tmp = new MenuItem("Leave Special Debit/Credit",null,null, mL14) );
tmp.mnemonic = '';
mLR01.add(tmp = new MenuItem("Leave Accounting","/wap/ppms/Reports/formats/Leave/leave_reg_arr.rpt?user0=report&password0=report"));tmp.mnemonic = ' ';mM01.add(tmp = new MenuItem("Entry of Extra Vacancies",null,null, mM11) );
tmp.mnemonic = '';
mM01.add(tmp = new MenuItem("Quota Register",null,null, mM12) );
tmp.mnemonic = '';
mM01.add(tmp = new MenuItem("Reports",null,null, mM13) );
tmp.mnemonic = '';
mM13.add(tmp = new MenuItem("Scale check (year wise)","/wap/ppms/bos/Scale_check.aspx"))
mM01.add(tmp = new MenuItem("Roster","/wap/ppms//bos/assesmentofVacancies.aspx"));tmp.mnemonic = '';mM01.add(tmp = new MenuItem("Cadre Control Register",null,null, mM15) );
tmp.mnemonic = '';
mM01.add(tmp = new MenuItem("BOS Posts Updation","/wap/ppms/bos/RosterEdit.aspx?mode=add"));tmp.mnemonic = '';mM01.add(tmp = new MenuItem("Roster Sanctions Updation","/wap/ppms/bos/frmRosterHeaderUpdation.aspx"));tmp.mnemonic = '';mP01.add(tmp = new MenuItem("View Brief Details",null,null, mP101) );
tmp.mnemonic = ' ';
mQ00.add(tmp = new MenuItem("Application",null,null, mQ001) );
tmp.mnemonic = ' ';
mQ00.add(tmp = new MenuItem("Priority Register",null,null, mQ01) );
tmp.mnemonic = '';
mQ00.add(tmp = new MenuItem("Quarter Allotment",null,null, mQ02) );
tmp.mnemonic = '';
mQ00.add(tmp = new MenuItem("Quarters Occ./Vacation",null,null, mQ03) );
tmp.mnemonic = '';
mQ00.add(tmp = new MenuItem("Edit Recoveries","/wap/ppms/quarters/frmEditQuarterMast.aspx"));tmp.mnemonic = ' ';mQYM.add(tmp = new MenuItem("HR-General Queries","/wap/ppms/hrquery.aspx"));tmp.mnemonic = '';m167.add(tmp = new MenuItem("Add","/wap/ppms/attendance/miscAttendanceDetails.aspx?mode=add"));tmp.mnemonic = '';m167.add(tmp = new MenuItem("Edit","/wap/ppms/attendance/miscAttendanceDetails.aspx?mode=edit"));tmp.mnemonic = '';m167.add(tmp = new MenuItem("Delete","/wap/ppms/attendance/miscAttendanceDetails.aspx?mode=delete"));tmp.mnemonic = '';m281.add(tmp = new MenuItem("Modify Employee Details","/wap/ppms/personnel/modifyemployeePayrates.aspx"));tmp.mnemonic = '';m281.add(tmp = new MenuItem("Pay Rates",null,null, m359) );
tmp.mnemonic = '';
m282.add(tmp = new MenuItem("Career Changes",null,null, m299) );
tmp.mnemonic = '';
m366.add(tmp = new MenuItem("Regular Fixed Deductions",null,null, m367) );
tmp.mnemonic = '';
m366.add(tmp = new MenuItem("Installment Based Dedns.",null,null, m368) );
tmp.mnemonic = '';
mC01.add(tmp = new MenuItem("Minus Earnings",null,null, mC59) );
tmp.mnemonic = ' ';
mC011.add(tmp = new MenuItem("Add","/wap/ppms/transactions/trainingDuty.aspx?mode=add"));tmp.mnemonic = ' ';mC011.add(tmp = new MenuItem("Edit","/wap/ppms/transactions/trainingDuty.aspx?mode=edit"));tmp.mnemonic = ' ';mC011.add(tmp = new MenuItem("Delete","/wap/ppms/transactions/trainingDuty.aspx?mode=delete"));tmp.mnemonic = ' ';mC011.add(tmp = new MenuItem("View","/wap/ppms/transactions/trainingDuty.aspx?mode=view"));tmp.mnemonic = ' ';mC011.add(tmp = new MenuItem("Check List","/wap/ppms/transactions/frmSupervisorAbsence.aspx"));tmp.mnemonic = ' ';mC011.add(tmp = new MenuItem("Incetive","/wap/ppms/DAArrears/DAArrInc.rpt?user0=report&password0=report"));tmp.mnemonic = ' ';mC12.add(tmp = new MenuItem("Add","/wap/ppms/attendance/miscAttendanceDetails.aspx?mode=add"));tmp.mnemonic = '';mC12.add(tmp = new MenuItem("Modify","/wap/ppms/attendance/miscAttendanceDetails.aspx?mode=edit"));tmp.mnemonic = '';mC12.add(tmp = new MenuItem("Delete","/wap/ppms/attendance/miscAttendanceDetails.aspx?mode=delete"));tmp.mnemonic = '';mC12.add(tmp = new MenuItem("View","/wap/ppms/attendance/miscAttendanceDetails.aspx?mode=view"));tmp.mnemonic = '';mC20.add(tmp = new MenuItem("Add","/wap/ppms/payroll/Miscelleneous.aspx?mode=add&type=MS"));tmp.mnemonic = '';mC20.add(tmp = new MenuItem("Edit","/wap/ppms/payroll/Miscelleneous.aspx?mode=edit&type=MS"));tmp.mnemonic = '';mC20.add(tmp = new MenuItem("View","/wap/ppms/payroll/MiscelleneousView.aspx?mode=view&type=MS"));tmp.mnemonic = ' ';mC21.add(tmp = new MenuItem("Add","/wap/ppms/payroll/standard.aspx?mode=add&type=OD"));tmp.mnemonic = '';mC21.add(tmp = new MenuItem("Edit","/wap/ppms/payroll/standard.aspx?mode=edit&type=OD"));tmp.mnemonic = '';mC21.add(tmp = new MenuItem("View","/wap/ppms/payroll/standard.aspx?mode=view&type=OD"));tmp.mnemonic = ' ';mC22.add(tmp = new MenuItem("ADD","/wap/ppms/payroll/Standard.aspx?mode=add&type=L%"));tmp.mnemonic = ' ';mC22.add(tmp = new MenuItem("EDIT","/wap/ppms/payroll/Standard.aspx?mode=edit&type=L%"));tmp.mnemonic = ' ';mC22.add(tmp = new MenuItem("VIEW","/wap/ppms/payroll/Standard.aspx?mode=view&type=L%"));tmp.mnemonic = ' ';mC23.add(tmp = new MenuItem("Add","/wap/ppms/PQRED"));tmp.mnemonic = '';mC23.add(tmp = new MenuItem("Edit","/wap/ppms/"));tmp.mnemonic = '';mC24.add(tmp = new MenuItem("Add","/wap/ppms/payroll/NonStandard.aspx?mode=add&type=NP"));tmp.mnemonic = '';mC24.add(tmp = new MenuItem("Edit","/wap/ppms/payroll/NonStandard.aspx?mode=edit&type=NP"));tmp.mnemonic = '';mC24.add(tmp = new MenuItem("View","/wap/ppms/payroll/NonStandard.aspx?mode=view&type=NP"));tmp.mnemonic = ' ';mC25.add(tmp = new MenuItem("Add","/wap/ppms/payroll/NonStandard.aspx?mode=add&type=NS"));tmp.mnemonic = ' ';mC25.add(tmp = new MenuItem("Edit","/wap/ppms/payroll/NonStandard.aspx?mode=edit&type=NS"));tmp.mnemonic = ' ';mC25.add(tmp = new MenuItem("View","/wap/ppms/payroll/NonStandard.aspx?mode=view&type=NS"));tmp.mnemonic = ' ';mC26.add(tmp = new MenuItem("Add","/wap/ppms/payroll/NonStandard.aspx?mode=add&type=NM"));tmp.mnemonic = '';mC26.add(tmp = new MenuItem("Edit","/wap/ppms/payroll/NonStandard.aspx?mode=edit&type=NM"));tmp.mnemonic = '';mC26.add(tmp = new MenuItem("View","/wap/ppms/payroll/NonStandard.aspx?mode=view&type=NM"));tmp.mnemonic = ' ';mC39.add(tmp = new MenuItem("Query","/wap/ppms/transactions/BankAccount.aspx?mode=view"));tmp.mnemonic = '';mC60.add(tmp = new MenuItem("Add","/wap/ppms/payroll/Standard.aspx?mode=add&type=AD"));tmp.mnemonic = ' ';mC60.add(tmp = new MenuItem("Edit","/wap/ppms/payroll/Standard.aspx?mode=edit&type=AD"));tmp.mnemonic = ' ';mC60.add(tmp = new MenuItem("Delete","/wap/ppms/payroll/Standard.aspx?mode=delete&type=AD"));tmp.mnemonic = ' ';mC60.add(tmp = new MenuItem("View","/wap/ppms/payroll/Standard.aspx?mode=view&type=AD"));tmp.mnemonic = ' ';mG01.add(tmp = new MenuItem("Car/Motor Cycle/Scooter/Computer","/wap/ppms/reports/formats/rptQuest/rptPFLogin.aspx?task_id=G11"));tmp.mnemonic = '';mG01.add(tmp = new MenuItem("Bicycle Loan","/wap/ppms/reports/formats/rptQuest/rptPFLogin.aspx?task_id=G12"));tmp.mnemonic = '';mG01.add(tmp = new MenuItem("Festival Loan","/wap/ppms/reports/formats/rptQuest/rptPFLogin.aspx?task_id=G13"));tmp.mnemonic = '';mG01.add(tmp = new MenuItem("HBA","/wap/ppms/reports/formats/rptQuest/rptPFLogin.aspx?task_id=G14"));tmp.mnemonic = '';mG030.add(tmp = new MenuItem("Car/Scooter/computer","/wap/ppms/loans/CarScooterComputer.aspx?mode=edit"));tmp.mnemonic = ' ';mG030.add(tmp = new MenuItem("BiCycle","/wap/ppms/loans/BicycleAdvance.aspx?mode=edit"));tmp.mnemonic = ' ';mG030.add(tmp = new MenuItem("Festival","/wap/ppms/loans/FestivalAdvance.aspx?mode=edit"));tmp.mnemonic = ' ';mG030.add(tmp = new MenuItem("HBA","/wap/ppms/loans/PurchaseOfLand.aspx?mode=edit"));tmp.mnemonic = ' ';mG25.add(tmp = new MenuItem("Bicycle Advance","/wap/ppms/loans/rptApplications.aspx?mode=B"));tmp.mnemonic = '';mG25.add(tmp = new MenuItem("Motor Car/Scooter Advance","/wap/ppms/loans/rptApplications.aspx?mode=C"));tmp.mnemonic = '';mG25.add(tmp = new MenuItem("Festival Advance","/wap/ppms/loans/rptApplications.aspx?mode=F"));tmp.mnemonic = '';mG25.add(tmp = new MenuItem("House Loans","/wap/ppms/loans/rptApplications.aspx?mode=H"));tmp.mnemonic = '';mG30.add(tmp = new MenuItem("Motor/Car/Scooter","/wap/ppms/loans/rptSanctions.aspx?mode=C"));tmp.mnemonic = '';mG30.add(tmp = new MenuItem("BiCycle","/wap/ppms/loans/rptSanctions.aspx?mode=B"));tmp.mnemonic = '';mG30.add(tmp = new MenuItem("Festival","/wap/ppms/loans/rptSanctions.aspx?mode=F"));tmp.mnemonic = '';mG30.add(tmp = new MenuItem("HBA","/wap/ppms/loans/rptSanctions.aspx?mode=H"));tmp.mnemonic = '';mG35.add(tmp = new MenuItem("Motor/Car/Scooter","/wap/ppms/loans/rptOONo.aspx?mode=C"));tmp.mnemonic = '';mG35.add(tmp = new MenuItem("BiCycle","/wap/ppms/loans/rptOONo.aspx?mode=B"));tmp.mnemonic = '';mG35.add(tmp = new MenuItem("Festival","/wap/ppms/loans/rptOONo.aspx?mode=F"));tmp.mnemonic = '';mG35.add(tmp = new MenuItem("HBA","/wap/ppms/loans/rptOONo.aspx?mode=H"));tmp.mnemonic = '';mL03.add(tmp = new MenuItem("Application Posting",null,null, mL04) );
tmp.mnemonic = '';
mL03.add(tmp = new MenuItem("Posting Leave Sanction","/wap/ppms/leave/postSanctionToApplicationForLeave.aspx?mode=post"));tmp.mnemonic = '';mL04.add(tmp = new MenuItem("Add","/wap/ppms/leave/leaveApplication.aspx?mode=add&task_id=L05"));tmp.mnemonic = '';mL04.add(tmp = new MenuItem("Cancel Leave","/wap/ppms/leave/editApplicationForLeave.aspx?mode=cancel"));tmp.mnemonic = '';mL04.add(tmp = new MenuItem("Delete","/wap/ppms/leave/editApplicationForLeave.aspx?mode=delete"));tmp.mnemonic = '';mL04.add(tmp = new MenuItem("Application Printing","/wap/ppms/Reports/formats/ApplicationForms/rptLeaveApplication.aspx?mode=rptLeaveApplication"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Add","/wap/ppms/leave/employeeLeaveMaster.aspx?mode=add"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Edit","/wap/ppms/leave/employeeLeaveMaster.aspx?mode=edit"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Delete","/wap/ppms/leave/employeeLeaveMaster.aspx?mode=delete"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Leave Crediting - I half","/wap/ppms/leave/FstHalfLeaveCredit.aspx"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Leave Master Report","/wap/ppms/Reports/formats/leave/leaveMaster.rpt?user0=report&password0=report"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Leave Crediting - II half","/wap/ppms/leave/SecondHalfLeaveCredit.aspx"));tmp.mnemonic = '';mL10.add(tmp = new MenuItem("Retrospective Leave Cr/Db","/wap/ppms/leave/leaveRetrospectivePosting.aspx"));tmp.mnemonic = '';mL14.add(tmp = new MenuItem("Add","/wap/ppms/leave/leaveSpecialDeditCredit.aspx?mode=add"));tmp.mnemonic = '';mL14.add(tmp = new MenuItem("Edit","/wap/ppms/leave/leaveSpecialDeditCredit.aspx?mode=edit"));tmp.mnemonic = '';mL14.add(tmp = new MenuItem("Delete","/wap/ppms/leave/leaveSpecialDeditCredit.aspx?mode=delete"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("GenerateMemorandum","/wap/ppms/leave/leaveMemorandum.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Special Credit","/wap/ppms/leave//leaveSpecialDeditCredit.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Print Memorandum","/wap/ppms/leave/rptLeaveMemorandum.aspx?mode=memorandum"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("CheckList(Leave posting)","/wap/ppms/Reports/formats/leave/leavePostingCheckList.aspx?mode=leaveAbsenseCheckList.rpt"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Leave Account Statement","/wap/ppms/leave/frmLeaveAnnualStatement.aspx?mode=employee"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Leave Ann Statement","/wap/ppms/leave/frmLeaveAnnualStatement.aspx?mode=paycategory"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Print Memo Bill unit","/wap/ppms/Reports/formats/leave/FrmLVbuEmp.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Retrospective Posting","/wap/ppms/leave/leaveRetrospectivePosting.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Post Unpaid holiday","/wap/ppms/leave/leaveUpdationForUnpaidHoliday.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Print leave clash unpaid","/wap/ppms/leave/lavanya.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Print attend. clash unpaid","/wap/ppms/leave/lavanya.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Unpaid Holiday - LAP/LHAP","/wap/ppms/leave/leaveUpdationForUnpaidHoliday.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Posting from application","/wap/ppms/leave/lavanya.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Leave Query","/wap/ppms/leave/leaveQuery.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Last Pay Certificate","/wap/ppms/lpc/rptLastCertificate.aspx"));tmp.mnemonic = '';mL50.add(tmp = new MenuItem("Print Regularisation","/wap/ppms/Reports/formats/leave/leavePostingCheckList1.aspx?mode=leaveREG"));tmp.mnemonic = ' ';mL50.add(tmp = new MenuItem("Leave Regularisation For a Particular Employee","/wap/ppms/Reports/formats/leave/leavePostingCheckList2.aspx"));tmp.mnemonic = ' ';
mM11.add(tmp = new MenuItem("Add","/wap/ppms//bos/entryofExtraVacancies.aspx?mode=add"));tmp.mnemonic = '';mM11.add(tmp = new MenuItem("Modify","/wap/ppms//bos/entryofExtraVacancies.aspx?mode=edit"));tmp.mnemonic = '';mM11.add(tmp = new MenuItem("Delete","/wap/ppms//bos/entryofExtraVacancies.aspx?mode=delete"));tmp.mnemonic = '';mM11.add(tmp = new MenuItem("Query","/wap/ppms//bos/entryofExtraVacancies.aspx?mode=view"));tmp.mnemonic = '';mM12.add(tmp = new MenuItem("Add","/wap/ppms//bos/quotaRegister.aspx?mode=add"));tmp.mnemonic = '';mM12.add(tmp = new MenuItem("Modify","/wap/ppms//bos/quotaRegister.aspx?mode=edit"));tmp.mnemonic = '';mM12.add(tmp = new MenuItem("Delete",""));tmp.mnemonic = '';mP101.add(tmp = new MenuItem("On Code","/wap/ppms/employee/EmployeeDetailsOnCode.aspx"));tmp.mnemonic = ' ';mP101.add(tmp = new MenuItem("On Name","/wap/ppms/employee/EmployeeDetailsOnName.aspx"));tmp.mnemonic = ' ';mQ001.add(tmp = new MenuItem("Entry",null,null, mQ002) );
tmp.mnemonic = ' ';
mQ001.add(tmp = new MenuItem("Print","/wap/ppms/QuarterAllotment/QuarAllotRept.aspx"));tmp.mnemonic = ' ';mQ01.add(tmp = new MenuItem("Add","/wap/ppms//quarters/QuarterPriorityRegister.aspx?mode=add"));tmp.mnemonic = '';mQ01.add(tmp = new MenuItem("Edit","/wap/ppms/quarters/QuarterPriorityRegister.aspx?mode=edit"));tmp.mnemonic = '';mQ01.add(tmp = new MenuItem("Delete","/wap/ppms/quarters/QuarterPriorityRegister.aspx?mode=delete"));tmp.mnemonic = '';mQ01.add(tmp = new MenuItem("Query","/wap/ppms/quarters/QuarterPriorityRegister.aspx?mode=view"));tmp.mnemonic = '';mQ02.add(tmp = new MenuItem("Create Noting","/wap/ppms/quarters/quarterAllotmentNoting.aspx?mode=add"));tmp.mnemonic = '';mQ02.add(tmp = new MenuItem("Add Employee","/wap/ppms/quarters/quarterAllotmentNoting.aspx?mode=add"));tmp.mnemonic = '';mQ02.add(tmp = new MenuItem("Modify Employee","/wap/ppms/quarters/quarterAllotmentNoting.aspx?mode=edit"));tmp.mnemonic = '';mQ02.add(tmp = new MenuItem("Delete Employee","/wap/ppms/quarters/quarterAllotmentNoting.aspx?mode=delete"));tmp.mnemonic = '';mQ02.add(tmp = new MenuItem("Print Noting","/wap/ppms/PPQTR1"));tmp.mnemonic = '';mQ02.add(tmp = new MenuItem("Generate Allotment Memo","/wap/ppms/quarters/quarterOfficeOrderNumber.aspx"));tmp.mnemonic = '';mQ02.add(tmp = new MenuItem("Print Allotment Memo","/wap/ppms/QuarterAllotment/QuarAllotRept.aspx"));tmp.mnemonic = '';mQ03.add(tmp = new MenuItem("Occupation","/wap/ppms//quarters/quartersOccupation.aspx?mode=add"));tmp.mnemonic = '';mQ03.add(tmp = new MenuItem("Non Occupeid Allotments","/wap/ppms/quarters/quarterdetailsreport.aspx"));tmp.mnemonic = '';mQ03.add(tmp = new MenuItem("Vaccation","/wap/ppms//quarters/quarterVacation.aspx?mode=add"));tmp.mnemonic = '';mQ03.add(tmp = new MenuItem("Quarters Ledger","/wap/ppms/quarters/quarterdetailsreport.aspx"));tmp.mnemonic = '';mQ03.add(tmp = new MenuItem("Occ./Vacation Report","/wap/ppms/quarters/quarterdetailsreport.aspx"));tmp.mnemonic = '';mQ03.add(tmp = new MenuItem("Query","/wap/ppms/quarters/quarter_query.rpt?user0=report&password0=report"));tmp.mnemonic = '';m299.add(tmp = new MenuItem("Create","/wap/ppms/personnel/careerEventsGeneration.aspx?mode=add"));tmp.mnemonic = '';m299.add(tmp = new MenuItem("Modify","/wap/ppms/personnel/careerEventsGeneration.aspx?mode=edit"));tmp.mnemonic = '';m299.add(tmp = new MenuItem("View","/wap/ppms/personnel/careerEventsGeneration.aspx?mode=view"));tmp.mnemonic = '';m359.add(tmp = new MenuItem("Create","/wap/ppms/personnel/employeePayrates.aspx?mode=add"));tmp.mnemonic = '';m359.add(tmp = new MenuItem("Modify","/wap/ppms/personnel/employeePayrates.aspx?mode=edit"));tmp.mnemonic = '';m359.add(tmp = new MenuItem("View","/wap/ppms/personnel/employeePayrates.aspx?mode=view"));tmp.mnemonic = '';m359.add(tmp = new MenuItem("Checklist Codewise","/wap/ppms/personnel/empchecklistCodewise.aspx"));tmp.mnemonic = '';m359.add(tmp = new MenuItem("Delete","/wap/ppms/personnel/employeePayrates.aspx?mode=delete"));tmp.mnemonic = ' ';m367.add(tmp = new MenuItem("Employee Wise","/wap/ppms/PQRED"));tmp.mnemonic = '';m367.add(tmp = new MenuItem("Erng/Dedn Code Wise","/wap/ppms/PQRED"));tmp.mnemonic = '';m368.add(tmp = new MenuItem("Employee Wise","/wap/ppms/PQRDE"));tmp.mnemonic = '';m368.add(tmp = new MenuItem("Erng/Dedn Code Wise","/wap/ppms/PQRDE"));tmp.mnemonic = '';mC59.add(tmp = new MenuItem("Add","/wap/ppms/payroll/Standard.aspx?mode=add&type=ME"));tmp.mnemonic = ' ';mC59.add(tmp = new MenuItem("Edit","/wap/ppms/payroll/Standard.aspx?mode=edit&type=ME"));tmp.mnemonic = ' ';mC59.add(tmp = new MenuItem("View","/wap/ppms/payroll/Standard.aspx?mode=view&type=ME"));tmp.mnemonic = ' ';mG21.add(tmp = new MenuItem("Application Number wise","/wap/ppms/loans/CarScooterComputer.aspx?mode=post"));tmp.mnemonic = ' ';mG21.add(tmp = new MenuItem("Pay-Category wise","/wap/ppms/loans/CarScooterComputerSanction.aspx"));tmp.mnemonic = ' ';mQ002.add(tmp = new MenuItem("Add","/wap/ppms/quarters/quarterApplication.aspx?mode=add"));tmp.mnemonic = ' ';mQ002.add(tmp = new MenuItem("Edit","/wap/ppms/quarters/quarterApplication.aspx?mode=edit"));tmp.mnemonic = ' ';mQ002.add(tmp = new MenuItem("Delete","/wap/ppms/quarters/quarterApplication.aspx?mode=delete"));tmp.mnemonic = ' ';mC01.add(tmp = new MenuItem("Arrear Deduction",null,null, mC60) );
tmp.mnemonic = ' ';
mG02.add(tmp = new MenuItem("Car/Motor Cycle/Scooter/Computer Loan",null,null, mG21) );
tmp.mnemonic = '';
mG02.add(tmp = new MenuItem("Bicycle Loan","/wap/ppms/loans/BicycleSanction.aspx?mode=post"));tmp.mnemonic = '';mG02.add(tmp = new MenuItem("Festival Loan","/wap/ppms/loans/FestivalSanction.aspx?mode=post"));tmp.mnemonic = '';mG02.add(tmp = new MenuItem("HBA","/wap/ppms/loans/PurchaseOfLand.aspx?mode=post"));tmp.mnemonic = '';
var menuBar = new MenuBar();
menuBar.add( tmp = new MenuButton("Attendance", m004) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Book Of Sanction", mM01) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Employee", mP01) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Govt.Loans", mG00) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Leave Accounting", mL02) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Payroll", m006) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Personnel", m278) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Quarters", mQ00) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Transactions", mC01) );
tmp.mnemonic = '';
menuBar.add( tmp = new MenuButton("Leave Regn. Arrears", mLR01) );
tmp.mnemonic = ' ';
menuBar.add( tmp = new MenuButton("HR-QUERIES", mQYM) );
tmp.mnemonic = '';

menuBar.write();
