'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MetlabReports
    
    '''<summary>
    '''PCORepo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PCORepo As Global.System.Web.UI.HtmlControls.HtmlLink
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnVEEGUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVEEGUM As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSTEELSHOTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSTEELSHOTS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSLAG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSLAG As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGAZEBINDER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGAZEBINDER As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGAZETUBE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGAZETUBE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDOMEDISC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDOMEDISC As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCOATEDSAND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCOATEDSAND As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnALMSTAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnALMSTAR As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAIRSETMORTOR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAIRSETMORTOR As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnABSGASKET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnABSGASKET As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCERNONABSGASKET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCERNONABSGASKET As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCLAYGRAPSTOPPER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCLAYGRAPSTOPPER As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCMC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCMC As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCRUSRAWDOLOMITE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCRUSRAWDOLOMITE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDELTACASTABLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDELTACASTABLE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDRINKWATER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDRINKWATER As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDryRAMMASS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDryRAMMASS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFLOURANCHALK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFLOURANCHALK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFLOUSPHAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFLOUSPHAR As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFUSEDSILICASAND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFUSEDSILICASAND As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGARLOCKPOURTUBEGASKET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGARLOCKPOURTUBEGASKET As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGRAPHMOULDBLANKET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGRAPHMOULDBLANKET As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGUNNINGMASS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGUNNINGMASS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnHDDRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHDDRM As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnHEXAMINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHEXAMINE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnINGATESLEEVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnINGATESLEEVE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnLADLEINSULATMATERIAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLADLEINSULATMATERIAL As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnMSPLATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMSPLATE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPOURINGTUBE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPOURINGTUBE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnWETRAMMINGMASS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWETRAMMINGMASS As Global.System.Web.UI.WebControls.Button
End Class
